### ISSUE TITLE
Funder needs for org IDs

### ISSUE THREAD

**Issue by RachaelKotarski** [datacite/freya#43]
“As a funder, we want to be able to internally identify past and present affiliated institutes and their names over time, so that we can associate them with their related host institutions, staff, outputs and accolades.”

**Comment by RachaelKotarski** [comment]
This was a discussion with a specific funder, we'll see if they're ok with being named!

**Comment by vasilyb** [comment]
Funders are not the only kind of stakeholders that will benefit from having universal PIDs for organizations. We need a wider discussion about Org IDs in FREYA. It will be good if many partners contribute to this user strory, so that we can have a balanced view of what is possible and what is worth doing about PIDs for organizations.

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/funder-needs-for-org-ids/94
